spring:
  application:
    name: pay
server:
  port: 8888
  
  
eureka:
  client:
    eureka-server-connect-timeout-seconds: 5000
    service-url:
      defaultZone: http://localhost:8761/eureka/