server:
  port: 8088

converter:  date:    format:    - yyyy-MM-dd

spring:  application:    name: consumer  redis:    port: 6379
    host: localhost
    database: 0
  jackson:    date-format: yyyy-MM-dd
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka/
shiro:
  redis:    host: localhost
    database: 1
    port: 6379  session:    global-session-timeout: 1200000
  shiro-filter:    filter-chain-definition-map:      /**: anon
      